### ISSUE TITLE
LLDB library not found

### ISSUE THREAD

**Issue by nikotidar** [aktsk/ipa-medit#8]
Error message
```sh
BoAAAA :: ~ » ipa-medit -bin="./Payload/Stockbit.app/Stockbit" -id="stockbit.com.stockbit"
Target device's UDID: 00008020-001640820230003A
Start to proxy a debugserver connection from a device for remote debugging...
Target app: /private/var/containers/Bundle/Application/3C76BDF3-755B-4E15-938B-F96E4B9108BE/Stockbit.app
Target local bin: ./Payload/Stockbit.app/Stockbit
Target platform: remote-ios
LLDB library not found... Please install Xcode.
```
System Information
```sh
BoAAAA :: ~ » sw_vers
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
```
Xcode Version
```sh
BoAAAA :: ~ » xcode-select -v                                                                                                                                    1 ↵
xcode-select version 2384.
BoAAAA :: ~ »
```

**Comment by tkmru** [comment]
The lldb python library inside xcode is used by ipa-medit.
Does `/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3/lldb` exist?

If it does not exist, run the following command:

```
$ xcode-select --install
```

**Comment by simhigo** [comment]
i have same problem
my lldb path only "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb" 
i don't have "Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3/lldb"
![image](https://user-images.githubusercontent.com/1684328/131450448-417ee0d3-bf1a-4099-8e7b-0632a89384f8.png)

**Comment by tkmru** [comment]
Hmm, the contents of the directory are different from my environment.

```
$ ls /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/
Clang/          Info.plist      Python/         Python3/        darwin-debug*   debugserver*    lldb-argdumper* repl_swift*     version.plist
```

What version of Xcode do you have?
I'm thinking of changing the implementation to look at the `Python/lldb` if there is no `Python3/lldb`.

**Comment by tkmru** [comment]
It's now fixed in v0.2.2, so you can use it.
[Release v0.2.2 · aktsk/ipa-medit](https://github.com/aktsk/ipa-medit/releases/tag/v0.2.2)

**Comment by nikotidar** [comment]
> It's now fixed in v0.2.2, so you can use it.
> [Release v0.2.2 · aktsk/ipa-medit](https://github.com/aktsk/ipa-medit/releases/tag/v0.2.2)

Thanks for updates.
`ipa-medit` still can't find LLDB Library path on latest version anyway

```sh
BoAAAA :: ~/Pentest/STOCKBIT » ipa-medit -bin Payload/Stockbit.app/stockBit -id stockbit.com.stockbit

Target device's UDID: 7a26f86d2d9750407ca4990d2c5cfb6f86feeaf8
Start to proxy a debugserver connection from a device for remote debugging...
Target app: /private/var/containers/Bundle/Application/EDF8B097-49BD-4860-90F6-DE8C86102228/Stockbit.app
Target local bin: Payload/Stockbit.app/stockBit
Target platform: remote-ios
LLDB library not found... Please install Xcode.
```

**Comment by tkmru** [comment]
In my environment, the lldb folder exists in `/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3` and can be imported from python.

```
$ cd /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3
lldb/
$ xcrun python3
Python 3.8.2 (default, Sep 24 2020, 19:37:08) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lldb
>>> exit()
```

How about in `/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python` of yours?
What version of Xcode do you have? The version of xcode-select is not the version of Xcode.

**Comment by simhigo** [comment]
update binary run same error.

i'm xcrun python3
![image](https://user-images.githubusercontent.com/1684328/131614504-760e471e-7cbf-4a3d-8db7-c8f04b1d8320.png)
and "xcode-select --install" command execute 
![image](https://user-images.githubusercontent.com/1684328/131614581-c56faae7-ba3d-4c35-bd3f-44bd49e74e22.png)

**Comment by nikotidar** [comment]
> @nikotidar
> 
> In my environment, the lldb folder exists in `/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3` and can be imported from python.
> 
> ```
> $ cd /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python3
> lldb/
> $ xcrun python3
> Python 3.8.2 (default, Sep 24 2020, 19:37:08) 
> [Clang 12.0.0 (clang-1200.0.32.21)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import lldb
> >>> exit()
> ```
> 
> How about in `/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python` of yours?
> What version of Xcode do you have? The version of xcode-select is not the version of Xcode.

@tkmru It's a slight difference between your environment and mine.

```sh
BoAAAA :: Resources/Python/lldb » cd /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources
BoAAAA :: SharedFrameworks/LLDB.framework/Resources » ls
Clang  Info.plist  Python  Python2  darwin-debug  debugserver  lldb-argdumper  repl_swift  version.plist
BoAAAA :: SharedFrameworks/LLDB.framework/Resources » xcrun python3
Python 3.8.2 (default, Jun  8 2021, 11:59:35)
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python')
>>> import lldb
>>>
```

**Comment by tkmru** [comment]
Probably the local lldb-driver.py has not been updated. Please delete lldb-driver.py.

```
$ rm ~/go/bin/lldb-driver.py
```

And run ipa-medit again.

**Comment by tkmru** [comment]
My comment got a reaction, so it seems to have worked in your environment.
I've also created a pull request to fix this issue, so I'm going to close this issue.

**Comment by simhigo** [comment]
fix it 
thanks you
